version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15s sh -c "until docker info; do echo .; sleep 1; done"
      - pip install requests
  pre_build:
    commands:
      - # We set AWS_ACCOUNT_ID as an enviornment variable in the CloudFormation template which creates this CodeBuild job.
      - # We assume that the region that the CodeBuild nodes are running (AWS_DEFAULT_REGION) is the same as all other stack resource.
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - MAIN_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME-main
      - VERSION_ID=v_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$VERSION_ID
  build:
    commands:
      - echo Build started on `date`
      - # ECS Main Service resources
      - echo ===== DOCKER BUILD =====
      - echo Building the Docker image from the Dockerfile.
      - docker build -t $MAIN_REPOSITORY_URI:latest $CODEBUILD_SRC_DIR/Phoenix/ecs
      - docker tag $MAIN_REPOSITORY_URI:latest $MAIN_REPOSITORY_URI:$IMAGE_TAG
      - # Lambda
      - echo ===== LAMBDA BUILD =====
      - # Upload the Python Lambda functions
      - listOfPythonLambdaFunctions='projects api_internals password_generator delete_network_interface'
      - |-
        for functionName in $listOfPythonLambdaFunctions
        do
          mkdir -p $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName
          cp -rf $CODEBUILD_SRC_DIR/Phoenix/lambda/$functionName/* $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName/
          cd $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName/
          pip install -r requirements.txt -t .
          zip -r lambda_function.zip ./*
          aws s3 cp lambda_function.zip s3://$LAMBDA_BUCKET_NAME/$VERSION_ID/$functionName/
          cd $CODEBUILD_SRC_DIR
          rm -rf $CODEBUILD_SRC_DIR/Phoenix/builds
        done
      - # Upload the NodeJS Lambda functions
      - listOfNodeJSLambdaFunctions='vpc_proxy'
      - |-
        for functionName in $listOfNodeJSLambdaFunctions
        do
          mkdir -p $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName
          cp -rf $CODEBUILD_SRC_DIR/Phoenix/lambda/$functionName/* $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName/
          cd $CODEBUILD_SRC_DIR/Phoenix/builds/$functionName/
          zip -r lambda_function.zip ./*
          aws s3 cp lambda_function.zip s3://$LAMBDA_BUCKET_NAME/$VERSION_ID/$functionName/
          cd $CODEBUILD_SRC_DIR
          rm -rf $CODEBUILD_SRC_DIR/Phoenix/builds
        done
  post_build:
    commands:
      - echo Build completed on `date`
      - # Notify Gitlab and alter t-ec2-params-template.json for merge request ecs deploy if certain environment variables are present (see the code for details)
      - python $CODEBUILD_SRC_DIR/Phoenix/merge_request_codebuild.py build
      - # Push docker files
      - echo Pushing the Docker images...
      - docker push $MAIN_REPOSITORY_URI:latest
      - docker push $MAIN_REPOSITORY_URI:$IMAGE_TAG
