version: 0.2

env:
  parameter-store:
    GITLAB_ACCESS_TOKEN: codebuild-gitlab-access-token

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15s sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - # We set AWS_ACCOUNT_ID as an enviornment variable in the CloudFormation template which creates this CodeBuild job.
      - # We assume that the region that the CodeBuild nodes are running (AWS_DEFAULT_REGION) is the same as all other stack resource.
      - aws --version
      - PROJECT_NAME=$(aws ssm get-parameter --name microservice-project-name | jq '.Parameter.Value' | sed -e s/\"//g)
      - CODEBUILD_RESOLVED_SOURCE_VERSION='123'
      - GITLAB_PROJECT_ID='258'
      - MERGE_REQUEST_INTERNAL_ID='21'
      - PIPELINE_NAME='phoenix'
  build:
    commands:
      - echo Build started on `date`
      - |-
        echo "Writing a python-gitlab.cfg config file"
        cat << HERE >> $CODEBUILD_SRC_DIR/python-gitlab.cfg
        [global]
        default = gitlab
        ssl_verify = true
        timeout = 5
        api_version = 3

        [gitlab]
        url = https://gitlab.intranet.solarmosaic.com
        private_token = $GITLAB_ACCESS_TOKEN
        api_version = 4
        HERE
      - |-
        echo "Writing a gitlab API dockerfile"
        cat << HERE >> $CODEBUILD_SRC_DIR/Dockerfile
        FROM python:slim

        # Install python-gitlab
        RUN pip install --upgrade python-gitlab

        # Copy sample configuration file
        COPY python-gitlab.cfg /

        # Define the entrypoint that enable a configuration file
        ENTRYPOINT ["gitlab", "--config-file", "/python-gitlab.cfg"]
        HERE
      - docker build -t python-gitlab:latest .
      - |-
        echo $CODEBUILD_RESOLVED_SOURCE_VERSION
        echo docker run -i -v $CODEBUILD_SRC_DIR/python-gitlab.cfg:/python-gitlab.cfg python-gitlab:latest project-merge-request-note create --project-id $GITLAB_PROJECT_ID --mr-iid $MERGE_REQUEST_INTERNAL_ID --body '<a href="https://console.aws.amazon.com/codepipeline/home?region='$AWS_DEFAULT_REGION'#/view/'$$PIPELINE_NAME'">Build Status</a> &nbsp; &nbsp; :thumbsup: @ commit '$CODEBUILD_RESOLVED_SOURCE_VERSION
        docker run -i -v $CODEBUILD_SRC_DIR/python-gitlab.cfg:/python-gitlab.cfg python-gitlab:latest project-merge-request-note create --project-id $GITLAB_PROJECT_ID --mr-iid $MERGE_REQUEST_INTERNAL_ID --body '<a href="https://console.aws.amazon.com/codepipeline/home?region='$AWS_DEFAULT_REGION'#/view/'$$PIPELINE_NAME'">Build Status</a> &nbsp; &nbsp; :thumbsup: @ commit '$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
