version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15s sh -c "until docker info; do echo .; sleep 1; done"
      - pip install requests
  pre_build:
    commands:
      - # We set AWS_ACCOUNT_ID as an enviornment variable in the CloudFormation template which creates this CodeBuild job.
      - # We assume that the region that the CodeBuild nodes are running (AWS_DEFAULT_REGION) is the same as all other stack resource.
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$PROJECT_NAME
      - VERSION_ID=v_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$VERSION_ID
  build:
    commands:
      - echo Build started on `date`
      - echo Enabling CloudFormation stack termination protection on production stacks.
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-database-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-ec2-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-ecs-main-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-lambda-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-api-custom-domain-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-api-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-api-internals-prod
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-api-deployment-prod
      - # V0 API Documentation
      - aws cloudformation update-termination-protection --enable-termination-protection --stack-name $PROJECT_NAME-api-documentation-v0-prod
      #- sbt scalastyle
  post_build:
    commands:
      - echo Build completed on `date`
