version: 0.2

env:
  parameter-store:
    ORGANIZATION_NAME: /microservice/phoenix/organization-name
    PROJECT_NAME: /microservice/phoenix/project-name
    DOMAIN: /microservice/phoenix/domain

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15s sh -c "until docker info; do echo .; sleep 1; done"
      - pip install requests
  pre_build:
    commands:
      - # We set AWS_ACCOUNT_ID as an enviornment variable in the CloudFormation template which creates this CodeBuild job.
      - # We assume that the region that the CodeBuild nodes are running (AWS_DEFAULT_REGION) is the same as all other stack resource.
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Destroying $PROJECT_NAME microservice
      - # Delete API Gateway deployments first
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-api-deployment-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-deployment-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-deployment-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-deployment-prod
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-deployment-testing
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-deployment-e2e
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-deployment-prod
      - # Delete API Gateway API Internals
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-api-internals-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-internals-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-internals-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-internals-prod
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-internals-testing
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-internals-e2e
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-internals-prod
      - # Delete API Gateway API
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-api-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-prod
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-testing
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-e2e
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-prod
      - # Delete Lambda
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-lambda-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-lambda-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-lambda-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-lambda-prod
      - # Delete ECS Main Task
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-ecs-main-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ecs-main-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ecs-main-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ecs-main-prod
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ecs-main-testing
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ecs-main-e2e
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ecs-main-prod
      - # Delete ECS
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-ec2-prod
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ec2-testing
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ec2-e2e
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ec2-prod
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ec2-testing
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ec2-e2e
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ec2-prod
      - # Delete Database
      - #aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-database-prod
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-database-testing
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-database-e2e
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-database-prod
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-database-testing
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-database-e2e
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-database-prod
      - # Delete API Gateway Custom Domain
      - #aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-api-custom-domain-prod
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-custom-domain-testing
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-custom-domain-e2e
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-custom-domain-prod
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-custom-domain-testing
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-custom-domain-e2e
      - #aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-api-custom-domain-prod
      - # Empty Microservice buckets
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-code-pipeline --recursive
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-code-build --recursive
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-lambda --recursive
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-microservice --recursive
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-encrypted-secrets --recursive
      - aws s3 rm s3://$ORGANIZATION_NAME-$PROJECT_NAME-load-balancer-logs --recursive
      - # Empty V0 API Documentation buckets
      - aws s3 rm s3://v0-testing.docs.$DOMAIN --recursive
      - aws s3 rm s3://v0-e2e.docs.$DOMAIN --recursive
      - aws s3 rm s3://v0.docs.$DOMAIN --recursive # Prod
      - # Delete V0 API Documentation CloudFront distro, S3 bucket, WAF, etc.
      - #aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-api-documentation-v0-prod
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-documentation-v0-testing
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-documentation-v0-e2e
      - #aws cloudformation delete-stack --stack-name $PROJECT_NAME-api-documentation-v0-prod
      - # Delete the Project ECR repositories.
      - aws ecr delete-repository --repository-name $PROJECT_NAME-main --force
      - # Delete Microservice
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-microservice
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-microservice
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-microservice
      - # Delete SSM Params
      - aws cloudformation update-termination-protection --no-enable-termination-protection --stack-name $PROJECT_NAME-ssm-microservice-params
      - aws cloudformation delete-stack --stack-name $PROJECT_NAME-ssm-microservice-params
      - aws cloudformation wait stack-delete-complete --stack-name $PROJECT_NAME-ssm-microservice-params
  post_build:
    commands:
      - echo Build completed on `date`
