version: 0.2

env:
  parameter-store:
    GITLAB_ACCESS_TOKEN: codebuild-gitlab-access-token
    PROJECT_NAME: microservice-project-name

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15s sh -c "until docker info; do echo .; sleep 1; done"
      - pip install requests
  pre_build:
    commands:
      - # We set AWS_ACCOUNT_ID as an enviornment variable in the CloudFormation template which creates this CodeBuild job.
      - # We assume that the region that the CodeBuild nodes are running (AWS_DEFAULT_REGION) is the same as all other stack resource.
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - python $CODEBUILD_SRC_DIR/Phoenix/notify_gitlab.py
  post_build:
    commands:
      - echo Build completed on `date`
